const STORE='demayo_movie_studio_v1';
const blank={title:'',genre:'Christian',idea:'',duration:'5',audience:'Family-friendly',visualStyle:'Realistic live-action Filipino fantasy',ending:'Hopeful',actors:[],treatment:'',scenes:[],updatedAt:null};
let project=load();let saveTimer;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];

const ideas={
  Christian:{title:'Liwanag sa Gitna ng Ulan',idea:'Isang amang nawalan ng trabaho ang unti-unting nawawalan ng pag-asa. Sa gitna ng problema, isang simpleng panalangin ng kanyang anak ang nagpapaalala sa pamilya na hindi sila nag-iisa.'},
  Fantasy:{title:'Ang Huling Tagapagmana ng Liwanag',idea:'Isang ordinaryong dalaga mula sa isang baryo ang nakatuklas na siya ang huling tagapagmana ng liwanag. Kailangan niyang pag-isahin ang mga bantay ng apat na kaharian bago magising ang sinaunang hari ng kadiliman.'},
  'Family Drama':{title:'Ang Huling Hapag',idea:'Nagkahiwa-hiwalay ang magkakapatid dahil sa isang lumang sama ng loob. Nang magkasakit ang kanilang ina, kailangan nilang muling magsalo sa hapag at harapin ang katotohanan.'},
  Romance:{title:'Sa Dulo ng Lumang Tulay',idea:'Dalawang kababata ang muling nagkita sa kanilang probinsya matapos ang sampung taon, ngunit may pangakong kailangang tuparin bago nila mabigyan ng pangalawang pagkakataon ang pag-ibig.'},
  Mystery:{title:'Ang Bahay sa Puno ng Balete',idea:'Isang batang mamamahayag ang umuwi sa probinsya upang siyasatin ang pagkawala ng kanyang lolo at natuklasan ang lihim na matagal nang binabantayan ng buong baryo.'},
  Comedy:{title:'Si Tita at ang Viral na Ulam',idea:'Isang masungit ngunit mahusay maglutong tita ang aksidenteng naging viral. Kailangang tulungan siya ng kanyang mga pamangkin na harapin ang internet nang hindi nawawala ang sikreto ng pamilya.'},
  Children:{title:'Maya at ang Munting Bituin',idea:'Isang batang takot sa dilim ang nakatagpo ng munting bituin na naligaw. Sa kanilang paglalakbay pauwi, natutuhan niyang ang tunay na tapang ay ang pagtulong kahit natatakot.'}
};
const castByGenre={
  Christian:[['Daniel Reyes','Main character',38,'Man','Filipino father, warm brown eyes, short black hair, simple light-blue shirt and dark trousers','Mapagmahal, masipag, ngunit tahimik kapag nasasaktan'],['Mia Reyes','Daughter',9,'Girl','Young Filipina girl, long black hair in a ponytail, yellow dress and white shoes','Masayahin, mapagtiwala at palaging nananalangin'],['Elena Reyes','Wife',36,'Woman','Filipina mother, shoulder-length black hair, cream blouse and long blue skirt','Matatag, mahinahon at mapagbigay']],
  Fantasy:[['Amara Tala','Huling Tagapagmana',24,'Woman','realistic young Filipina heroine, warm brown skin, long wavy black hair, amber eyes, weathered ivory tunic, deep blue woven cloak, bronze sun pendant','Matapang at mahabagin ngunit natatakot sa kapangyarihang minana niya'],['Dagan Alon','Bantay ng Kaharian',30,'Man','realistic Filipino warrior, athletic build, short black hair, scar above left eyebrow, dark leather armour with indigenous Filipino geometric details, bronze sword','Tapat, mapagmatyag at handang magsakripisyo'],['Reyna Lira','Tagapag-ingat ng Liwanag',48,'Woman','regal Filipina queen, silver-streaked black hair, gold diadem, emerald ceremonial gown, luminous staff','Matalino, matatag at may lihim na kaugnayan sa kalaban'],['Haring Daruk','Hari ng Kadiliman',52,'Man','imposing Filipino dark king, angular face, long black hair with silver strands, obsidian armour, crimson cape, shadow crown','Mapanlinlang, makapangyarihan at naniniwalang siya ang tunay na tagapagligtas']],
  default:[['Ana Santos','Main character',30,'Woman','Filipina woman, expressive brown eyes, shoulder-length black hair, modest red blouse and denim jeans','Matapang, mapagmahal at determinado'],['Marco Cruz','Supporting character',33,'Man','Filipino man, short black hair, kind face, forest-green shirt and dark trousers','Tahimik, maparaan at tapat'],['Lola Rosa','Mentor',66,'Woman','Elderly Filipina woman, silver-streaked hair in a bun, floral dress and knitted shawl','Matalino, palabiro at mapagkalinga']]
};
const avatar={Woman:'👩🏽',Man:'👨🏽',Girl:'👧🏽',Boy:'👦🏽'};

function load(){try{return {...blank,...JSON.parse(localStorage.getItem(STORE))}}catch{return {...blank}}}
function save(){project.updatedAt=new Date().toISOString();localStorage.setItem(STORE,JSON.stringify(project));$('#saveStatus').textContent='Saved locally'}
function queueSave(){ $('#saveStatus').textContent='Saving…';clearTimeout(saveTimer);saveTimer=setTimeout(save,350)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,6)}
function currentGenre(){return $('input[name=genre]:checked')?.value||'Christian'}

function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.step').forEach(s=>s.classList.toggle('active',s.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='actors')renderActors();if(id==='script')renderScript();if(id==='storyboard')renderScenes();if(id==='export')renderMediaTimeline()}
$$('.step').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('.go').forEach(b=>b.onclick=()=>showView(b.dataset.go));

function syncForm(){$('#title').value=project.title;$('#idea').value=project.idea;$('#duration').value=project.duration;$('#audience').value=project.audience;$('#visualStyle').value=project.visualStyle;$('#ending').value=project.ending;const radio=$(`input[name=genre][value="${project.genre}"]`);if(radio)radio.checked=true;$('#ideaCount').textContent=project.idea.length}
function readForm(){project.title=$('#title').value.trim();project.idea=$('#idea').value.trim();project.genre=currentGenre();project.duration=$('#duration').value;project.audience=$('#audience').value;project.visualStyle=$('#visualStyle').value;project.ending=$('#ending').value}
$('#idea').addEventListener('input',e=>{if(e.target.value.length>800)e.target.value=e.target.value.slice(0,800);$('#ideaCount').textContent=e.target.value.length;readForm();queueSave()});$$('#storyForm input,#storyForm select').forEach(el=>el.addEventListener('change',()=>{readForm();queueSave()}));
$('#surpriseBtn').onclick=()=>{const genre=currentGenre(),x=ideas[genre];$('#title').value=x.title;$('#idea').value=x.idea;$('#ideaCount').textContent=x.idea.length;readForm();queueSave();toast('Story idea created')};
$('#storyForm').onsubmit=e=>{e.preventDefault();readForm();if(!project.title)project.title=ideas[project.genre].title;if(!project.idea)project.idea=ideas[project.genre].idea;if(!project.actors.length)generateCast();generateTreatment();generateScenes();save();syncForm();toast('Movie plan created');showView('actors')};

function generateCast(){const list=castByGenre[project.genre]||castByGenre.default;project.actors=list.map(x=>({id:uid(),name:x[0],role:x[1],age:x[2],gender:x[3],look:x[4],personality:x[5]}));save();renderActors()}
function renderActors(){const grid=$('#actorGrid');if(!project.actors.length){grid.innerHTML='<div class="panel"><h3>No actors yet</h3><p style="color:var(--muted)">Generate a suggested Filipino cast or add your own fictional actor.</p></div>';return}grid.innerHTML=project.actors.map(a=>`<article class="actor-card"><div class="actor-portrait">${avatar[a.gender]||'🎭'}<small>AI FICTIONAL ACTOR</small></div><div class="actor-body"><h3>${esc(a.name)}</h3><span>${esc(a.role)} · Age ${a.age}</span><p>${esc(a.look)}</p><div class="card-actions"><button class="secondary" data-edit="${a.id}">Edit</button><button class="secondary" data-delete="${a.id}">Remove</button></div></div></article>`).join('');$$('[data-edit]').forEach(b=>b.onclick=()=>openActor(b.dataset.edit));$$('[data-delete]').forEach(b=>b.onclick=()=>{project.actors=project.actors.filter(a=>a.id!==b.dataset.delete);save();renderActors()})}
$('#generateCastBtn').onclick=()=>{generateCast();toast('Suggested cast created')};$('#addActorBtn').onclick=()=>openActor();
function openActor(id){const a=project.actors.find(x=>x.id===id)||{id:'',name:'',role:'Main character',age:30,gender:'Woman',look:'Filipino actor, expressive brown eyes, black hair, modest contemporary clothing',personality:'Matapang, mabait at determinado'};$('#actorId').value=a.id;$('#actorName').value=a.name;$('#actorRole').value=a.role;$('#actorAge').value=a.age;$('#actorGender').value=a.gender;$('#actorLook').value=a.look;$('#actorPersonality').value=a.personality;$('#actorModal').classList.remove('hidden')}
$('#closeActorModal').onclick=()=>$('#actorModal').classList.add('hidden');$('#actorModal').onclick=e=>{if(e.target.id==='actorModal')e.currentTarget.classList.add('hidden')};
$('#actorForm').onsubmit=e=>{e.preventDefault();const a={id:$('#actorId').value||uid(),name:$('#actorName').value.trim(),role:$('#actorRole').value.trim(),age:+$('#actorAge').value,gender:$('#actorGender').value,look:$('#actorLook').value.trim(),personality:$('#actorPersonality').value.trim()};const i=project.actors.findIndex(x=>x.id===a.id);i<0?project.actors.push(a):project.actors[i]=a;save();renderActors();$('#actorModal').classList.add('hidden');toast('Actor saved')};

function generateTreatment(){const hero=project.actors[0]?.name||'ang pangunahing tauhan',support=project.actors[1]?.name||'isang kaibigan';project.treatment=`PAMAGAT: ${project.title}\nGENRE: ${project.genre}\nTONO: ${project.ending} ending · ${project.audience}\n\nLOGLINE\n${project.idea}\n\nSIMULA\nIpakilala si ${hero} sa isang pangkaraniwang araw sa Pilipinas. Ipakita agad ang pangarap, takot, at mahalagang relasyon ng pangunahing tauhan. Isang hindi inaasahang pangyayari ang sisira sa normal niyang mundo.\n\nGITNA\nHabang sinusubukan ni ${hero} na lutasin ang problema, lalong lumalaki ang kapalit. Tutulong si ${support}, ngunit isang maling desisyon ang magdadala sa kanila sa pinakamababang punto. Dito mahaharap ang pangunahing tauhan sa katotohanang matagal niyang iniiwasan.\n\nKASUKDULAN\nKailangang pumili ni ${hero}: manatili sa takot o gawin ang tama kahit walang kasiguruhan. Ang desisyong ito ang magpapakita ng tunay na tema ng kuwento.\n\nWAKAS\nMagbigay ng ${project.ending.toLowerCase()} na pagtatapos. Ipakita ang pagbabago sa tauhan sa pamamagitan ng isang simpleng visual callback mula sa unang eksena.\n\nMENSAHE\nAng pag-asa ay hindi kawalan ng problema—ito ang pagpiling magpatuloy at magmahal sa gitna nito.`}
function renderScript(){if(!project.treatment)generateTreatment();$('#scriptTitle').textContent=project.title||'Untitled Movie';$('#scriptGenre').textContent=project.genre;$('#scriptLength').textContent=`${project.duration} minutes`;$('#treatment').value=project.treatment}
$('#treatment').oninput=e=>{project.treatment=e.target.value;queueSave()};$('#regenerateScriptBtn').onclick=()=>{generateTreatment();renderScript();save();toast('Treatment regenerated')};

function generateScenes(){const n=Math.max(5,Math.round(+project.duration*1.2)),hero=project.actors[0]?.name||'Pangunahing Tauhan',support=project.actors[1]?.name||'Kaibigan';const beats=[['Ang Mundong Kilala','Ipakilala ang pangunahing tauhan at ang kanyang pang-araw-araw na mundo.',`${hero}: “Akala ko, magiging maayos ang lahat ngayong araw.”`],['Ang Hindi Inaasahan','Dumating ang pangyayaring magpapabago sa lahat.',`${support}: “May kailangan kang malaman.”`],['Unang Hakbang','Nagpasya ang pangunahing tauhan na harapin ang problema.',`${hero}: “Hindi ko alam kung kaya ko, pero susubukan ko.”`],['Mas Mabigat na Pagsubok','Nagkaroon ng pagkakamali at lumaki ang panganib.',`${hero}: “Kasalanan ko ito. Pero hindi pa huli ang lahat.”`],['Ang Pagpili','Hinarap ng pangunahing tauhan ang pinakamahirap na desisyon.',`${support}: “Anuman ang piliin mo, huwag mong kalimutan kung sino ka.”`],['Bagong Liwanag','Ipakita ang resulta, pagbabago at mensahe ng kuwento.',`${hero}: “Hindi man nawala ang ulan, natutuhan kong hanapin ang liwanag.”`]];project.scenes=Array.from({length:n},(_,i)=>{const b=beats[Math.round(i*(beats.length-1)/(n-1))];return{id:uid(),title:`Eksena ${i+1}: ${b[0]}`,action:b[1],dialogue:b[2],prompt:`${project.visualStyle}, cinematic Filipino setting, ${project.actors.map(a=>a.name+': '+a.look).join('; ')}, scene: ${b[1]}, expressive lighting, consistent character design, 16:9, no text`}})}
function renderScenes(){if(!project.scenes.length)generateScenes();$('#sceneCount').textContent=`${project.scenes.length} scenes`;$('#sceneList').innerHTML=project.scenes.map((s,i)=>`<article class="scene-card" data-scene="${s.id}"><div class="scene-number"><small>SCENE</small><strong>${String(i+1).padStart(2,'0')}</strong></div><div class="scene-content"><div class="scene-head"><input data-key="title" value="${attr(s.title)}" aria-label="Scene title"><button class="delete-button" data-remove="${s.id}">Remove</button></div><div class="scene-fields"><label class="full">ACTION<textarea data-key="action" rows="3">${esc(s.action)}</textarea></label><label>DIALOGUE<textarea data-key="dialogue" rows="4">${esc(s.dialogue)}</textarea></label><label>IMAGE PROMPT<textarea data-key="prompt" rows="4">${esc(s.prompt)}</textarea></label></div></div></article>`).join('');$$('[data-scene] input,[data-scene] textarea').forEach(el=>el.oninput=()=>{const s=project.scenes.find(x=>x.id===el.closest('[data-scene]').dataset.scene);s[el.dataset.key]=el.value;queueSave()});$$('[data-remove]').forEach(b=>b.onclick=()=>{project.scenes=project.scenes.filter(s=>s.id!==b.dataset.remove);save();renderScenes()})}
$('#addSceneBtn').onclick=()=>{project.scenes.push({id:uid(),title:`Eksena ${project.scenes.length+1}: Bagong Eksena`,action:'Ilarawan ang nangyayari sa eksenang ito.',dialogue:'TAUHAN: “Ilagay ang dialogue dito.”',prompt:`${project.visualStyle}, Filipino setting, cinematic lighting, 16:9, no text`});save();renderScenes()};

function productionText(){return `${project.title.toUpperCase()}\nDe Mayo AI Movie Studio Production Plan\n\nGenre: ${project.genre}\nLength: ${project.duration} minutes\nAudience: ${project.audience}\nStyle: ${project.visualStyle}\n\nSTORY IDEA\n${project.idea}\n\nCAST\n${project.actors.map(a=>`${a.name} — ${a.role}, age ${a.age}\nAppearance: ${a.look}\nPersonality: ${a.personality}`).join('\n\n')}\n\nSTORY TREATMENT\n${project.treatment}\n\nSCENES\n${project.scenes.map((s,i)=>`SCENE ${i+1}: ${s.title}\nAction: ${s.action}\nDialogue: ${s.dialogue}\nVisual prompt: ${s.prompt}`).join('\n\n')}\n\nCreated with De Mayo AI Movie Studio.`}
function download(name,data,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
$('#downloadTxtBtn').onclick=()=>download(`${slug(project.title)}-production-script.txt`,productionText());$('#downloadJsonBtn').onclick=()=>download(`${slug(project.title)}-project.json`,JSON.stringify(project,null,2),'application/json');
$('#youtubeBtn').onclick=()=>{const text=`TITLE\n${project.title} | Original Tagalog AI-Animated Story\n\nDESCRIPTION\nIsang original na kuwentong Tagalog tungkol sa ${project.genre.toLowerCase()}, pag-asa at mga desisyong humuhubog sa ating buhay.\n\nAng pelikulang ito ay gumagamit ng AI-assisted fictional characters, illustrations at production tools. Walang tunay na tao o pangyayari ang inilalarawan maliban kung malinaw na sinabi.\n\nCreated by De Mayo AI Movie Studio.\n\nHASHTAGS\n#KwentongTagalog #TagalogStory #AIMovie #FilipinoStories #DeMayoMovieStudio`;$('#youtubeText').value=text;$('#youtubePackage').classList.remove('hidden');toast('YouTube package created')};$('#copyPackageBtn').onclick=()=>navigator.clipboard.writeText($('#youtubeText').value).then(()=>toast('Copied'));
$('#restoreInput').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());project={...blank,...data};save();syncForm();toast('Project restored');showView('home')}catch{toast('This backup could not be restored')}};
$('#newProjectBtn').onclick=()=>{if(confirm('Start a new movie? Download a backup first if you want to keep this project.')){project={...blank,actors:[],scenes:[]};save();syncForm();showView('home');toast('New project ready')}};
function esc(v=''){return String(v).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}function attr(v=''){return esc(v).replace(/"/g,'&quot;')}function slug(v='movie'){return(v||'movie').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'movie'}

// Build 1.2 media is intentionally session-only: large files never enter localStorage.
const sceneMedia=new Map();let stopPlayback=false;
function mediaFor(id){if(!sceneMedia.has(id))sceneMedia.set(id,{image:null,imageUrl:'',audio:null,audioUrl:'',duration:6});return sceneMedia.get(id)}
function renderMediaTimeline(){
  const timeline=$('#mediaTimeline');
  if(!project.scenes.length){timeline.innerHTML='<p class="studio-note">Create your storyboard scenes first.</p>';updateMediaReady();return}
  timeline.innerHTML=project.scenes.map((s,i)=>{const m=mediaFor(s.id);return `<div class="media-row" data-media="${s.id}"><span class="media-index">${i+1}</span><div class="media-info"><strong>${esc(s.title)}</strong><small>${m.image?esc(m.image.name):'No image selected'}${m.audio?' · Audio: '+esc(m.audio.name):''}</small></div><div class="media-files"><label class="secondary ${m.image?'ready':''}">🖼 ${m.image?'Replace':'Add'} image<input data-image type="file" accept="image/*"></label><label class="secondary ${m.audio?'ready':''}">🔊 ${m.audio?'Replace':'Add'} audio<input data-audio type="file" accept="audio/*"></label><label>Seconds <input class="duration-input" data-duration type="number" min="2" max="60" step="1" value="${m.duration}"></label></div></div>`}).join('');
  $$('[data-media] [data-image]').forEach(input=>input.onchange=()=>setMediaFile(input,'image'));
  $$('[data-media] [data-audio]').forEach(input=>input.onchange=()=>setMediaFile(input,'audio'));
  $$('[data-media] [data-duration]').forEach(input=>input.onchange=()=>{mediaFor(input.closest('[data-media]').dataset.media).duration=Math.max(2,Math.min(60,+input.value||6))});
  updateMediaReady();
}
function setMediaFile(input,type){const file=input.files[0];if(!file)return;const m=mediaFor(input.closest('[data-media]').dataset.media),urlKey=type+'Url';if(m[urlKey])URL.revokeObjectURL(m[urlKey]);m[type]=file;m[urlKey]=URL.createObjectURL(file);renderMediaTimeline();toast(`${type==='image'?'Image':'Audio'} added`)}
function updateMediaReady(){const ready=project.scenes.filter(s=>mediaFor(s.id).image).length;$('#mediaReady').textContent=`${ready} / ${project.scenes.length} images ready`;$('#previewEmpty').classList.toggle('hidden',ready>0)}
function loadImage(url){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=url})}
function wait(ms){return new Promise(resolve=>setTimeout(resolve,ms))}
function wrapText(ctx,text,maxWidth){const words=(text||'').replace(/^[^:]+:\s*/, '').split(/\s+/),lines=[];let line='';for(const word of words){const test=line?line+' '+word:word;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=word}else line=test}if(line)lines.push(line);return lines.slice(0,3)}
function drawFrame(ctx,img,scene,progress,w,h){ctx.fillStyle='#05050a';ctx.fillRect(0,0,w,h);if(img){const scale=Math.max(w/img.width,h/img.height)*(1+.045*progress),dw=img.width*scale,dh=img.height*scale,x=(w-dw)/2-(progress-.5)*w*.025,y=(h-dh)/2;ctx.drawImage(img,x,y,dw,dh)}const shade=ctx.createLinearGradient(0,h*.55,0,h);shade.addColorStop(0,'transparent');shade.addColorStop(1,'rgba(0,0,0,.88)');ctx.fillStyle=shade;ctx.fillRect(0,0,w,h);if($('#burnSubtitles').checked){ctx.textAlign='center';ctx.font=`700 ${Math.round(w*.032)}px Arial`;ctx.lineWidth=Math.max(3,w*.004);ctx.strokeStyle='rgba(0,0,0,.95)';ctx.fillStyle='white';const lines=wrapText(ctx,scene.dialogue,w*.82),lineH=w*.042,start=h-w*.055*(lines.length);lines.forEach((line,i)=>{ctx.strokeText(line,w/2,start+i*lineH);ctx.fillText(line,w/2,start+i*lineH)})}}
async function playMovie(record=false){
  const usable=project.scenes.filter(s=>mediaFor(s.id).image);if(!usable.length){toast('Add at least one scene image first');return}
  stopPlayback=false;const canvas=$('#movieCanvas'),quality=+$('#renderQuality').value,ctx=canvas.getContext('2d');canvas.width=quality;canvas.height=Math.round(quality*9/16);$('#stopPreviewBtn').classList.remove('hidden');$('#renderStatus').textContent=record?'Rendering…':'Previewing…';
  let recorder,chunks=[],mime='',audioCtx=null,audioDest=null;if(record){const choices=['video/mp4;codecs=avc1','video/webm;codecs=vp9,opus','video/webm'];mime=choices.find(x=>MediaRecorder.isTypeSupported(x))||'';const stream=canvas.captureStream(30);audioCtx=new AudioContext();audioDest=audioCtx.createMediaStreamDestination();audioDest.stream.getAudioTracks().forEach(track=>stream.addTrack(track));recorder=new MediaRecorder(stream,mime?{mimeType:mime,videoBitsPerSecond:quality===1920?9000000:5000000}:undefined);recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.start(1000)}
  for(const scene of usable){if(stopPlayback)break;const m=mediaFor(scene.id),img=await loadImage(m.imageUrl),duration=m.duration*1000,start=performance.now();let audio=null;if(m.audioUrl){audio=new Audio(m.audioUrl);if(record&&audioCtx){const source=audioCtx.createMediaElementSource(audio);source.connect(audioDest);source.connect(audioCtx.destination)}audio.play().catch(()=>{})}while(!stopPlayback&&performance.now()-start<duration){const p=Math.min(1,(performance.now()-start)/duration);drawFrame(ctx,img,scene,p,canvas.width,canvas.height);await wait(33)}if(audio){audio.pause();audio.currentTime=0}}
  if(recorder&&recorder.state!=='inactive'){await new Promise(resolve=>{recorder.onstop=resolve;recorder.stop()});if(!stopPlayback){const ext=mime.includes('mp4')?'mp4':'webm',blob=new Blob(chunks,{type:mime||'video/webm'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${slug(project.title)}-youtube.${ext}`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);toast(`${ext.toUpperCase()} movie created`)}}
  if(audioCtx)audioCtx.close();$('#stopPreviewBtn').classList.add('hidden');$('#renderStatus').textContent=stopPlayback?'Stopped':'Complete';
}
$('#previewMovieBtn').onclick=()=>playMovie(false);$('#renderMovieBtn').onclick=()=>playMovie(true);$('#stopPreviewBtn').onclick=()=>{stopPlayback=true};
syncForm();
