const STORE='demayo_movie_studio_v1';
const blank={title:'',genre:'Christian',idea:'',duration:'5',audience:'Family-friendly',visualStyle:'Cinematic 3D animation',ending:'Hopeful',actors:[],treatment:'',scenes:[],updatedAt:null};
let project=load();let saveTimer;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];

const ideas={
  Christian:{title:'Liwanag sa Gitna ng Ulan',idea:'Isang amang nawalan ng trabaho ang unti-unting nawawalan ng pag-asa. Sa gitna ng problema, isang simpleng panalangin ng kanyang anak ang nagpapaalala sa pamilya na hindi sila nag-iisa.'},
  'Family Drama':{title:'Ang Huling Hapag',idea:'Nagkahiwa-hiwalay ang magkakapatid dahil sa isang lumang sama ng loob. Nang magkasakit ang kanilang ina, kailangan nilang muling magsalo sa hapag at harapin ang katotohanan.'},
  Romance:{title:'Sa Dulo ng Lumang Tulay',idea:'Dalawang kababata ang muling nagkita sa kanilang probinsya matapos ang sampung taon, ngunit may pangakong kailangang tuparin bago nila mabigyan ng pangalawang pagkakataon ang pag-ibig.'},
  Mystery:{title:'Ang Bahay sa Puno ng Balete',idea:'Isang batang mamamahayag ang umuwi sa probinsya upang siyasatin ang pagkawala ng kanyang lolo at natuklasan ang lihim na matagal nang binabantayan ng buong baryo.'},
  Comedy:{title:'Si Tita at ang Viral na Ulam',idea:'Isang masungit ngunit mahusay maglutong tita ang aksidenteng naging viral. Kailangang tulungan siya ng kanyang mga pamangkin na harapin ang internet nang hindi nawawala ang sikreto ng pamilya.'},
  Children:{title:'Maya at ang Munting Bituin',idea:'Isang batang takot sa dilim ang nakatagpo ng munting bituin na naligaw. Sa kanilang paglalakbay pauwi, natutuhan niyang ang tunay na tapang ay ang pagtulong kahit natatakot.'}
};
const castByGenre={
  Christian:[['Daniel Reyes','Main character',38,'Man','Filipino father, warm brown eyes, short black hair, simple light-blue shirt and dark trousers','Mapagmahal, masipag, ngunit tahimik kapag nasasaktan'],['Mia Reyes','Daughter',9,'Girl','Young Filipina girl, long black hair in a ponytail, yellow dress and white shoes','Masayahin, mapagtiwala at palaging nananalangin'],['Elena Reyes','Wife',36,'Woman','Filipina mother, shoulder-length black hair, cream blouse and long blue skirt','Matatag, mahinahon at mapagbigay']],
  default:[['Ana Santos','Main character',30,'Woman','Filipina woman, expressive brown eyes, shoulder-length black hair, modest red blouse and denim jeans','Matapang, mapagmahal at determinado'],['Marco Cruz','Supporting character',33,'Man','Filipino man, short black hair, kind face, forest-green shirt and dark trousers','Tahimik, maparaan at tapat'],['Lola Rosa','Mentor',66,'Woman','Elderly Filipina woman, silver-streaked hair in a bun, floral dress and knitted shawl','Matalino, palabiro at mapagkalinga']]
};
const avatar={Woman:'👩🏽',Man:'👨🏽',Girl:'👧🏽',Boy:'👦🏽'};

function load(){try{return {...blank,...JSON.parse(localStorage.getItem(STORE))}}catch{return {...blank}}}
function save(){project.updatedAt=new Date().toISOString();localStorage.setItem(STORE,JSON.stringify(project));$('#saveStatus').textContent='Saved locally'}
function queueSave(){ $('#saveStatus').textContent='Saving…';clearTimeout(saveTimer);saveTimer=setTimeout(save,350)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,6)}
function currentGenre(){return $('input[name=genre]:checked')?.value||'Christian'}

function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.step').forEach(s=>s.classList.toggle('active',s.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='actors')renderActors();if(id==='script')renderScript();if(id==='storyboard')renderScenes()}
$$('.step').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('.go').forEach(b=>b.onclick=()=>showView(b.dataset.go));

function syncForm(){$('#title').value=project.title;$('#idea').value=project.idea;$('#duration').value=project.duration;$('#audience').value=project.audience;$('#visualStyle').value=project.visualStyle;$('#ending').value=project.ending;const radio=$(`input[name=genre][value="${project.genre}"]`);if(radio)radio.checked=true;$('#ideaCount').textContent=project.idea.length}
function readForm(){project.title=$('#title').value.trim();project.idea=$('#idea').value.trim();project.genre=currentGenre();project.duration=$('#duration').value;project.audience=$('#audience').value;project.visualStyle=$('#visualStyle').value;project.ending=$('#ending').value}
$('#idea').addEventListener('input',e=>{if(e.target.value.length>800)e.target.value=e.target.value.slice(0,800);$('#ideaCount').textContent=e.target.value.length;readForm();queueSave()});$$('#storyForm input,#storyForm select').forEach(el=>el.addEventListener('change',()=>{readForm();queueSave()}));
$('#surpriseBtn').onclick=()=>{const genre=currentGenre(),x=ideas[genre];$('#title').value=x.title;$('#idea').value=x.idea;$('#ideaCount').textContent=x.idea.length;readForm();queueSave();toast('Story idea created')};
$('#storyForm').onsubmit=e=>{e.preventDefault();readForm();if(!project.title)project.title=ideas[project.genre].title;if(!project.idea)project.idea=ideas[project.genre].idea;if(!project.actors.length)generateCast();generateTreatment();generateScenes();save();syncForm();toast('Movie plan created');showView('actors')};

function generateCast(){const list=project.genre==='Christian'?castByGenre.Christian:castByGenre.default;project.actors=list.map(x=>({id:uid(),name:x[0],role:x[1],age:x[2],gender:x[3],look:x[4],personality:x[5]}));save();renderActors()}
function renderActors(){const grid=$('#actorGrid');if(!project.actors.length){grid.innerHTML='<div class="panel"><h3>No actors yet</h3><p style="color:var(--muted)">Generate a suggested Filipino cast or add your own fictional actor.</p></div>';return}grid.innerHTML=project.actors.map(a=>`<article class="actor-card"><div class="actor-portrait">${avatar[a.gender]||'🎭'}<small>AI FICTIONAL ACTOR</small></div><div class="actor-body"><h3>${esc(a.name)}</h3><span>${esc(a.role)} · Age ${a.age}</span><p>${esc(a.look)}</p><div class="card-actions"><button class="secondary" data-edit="${a.id}">Edit</button><button class="secondary" data-delete="${a.id}">Remove</button></div></div></article>`).join('');$$('[data-edit]').forEach(b=>b.onclick=()=>openActor(b.dataset.edit));$$('[data-delete]').forEach(b=>b.onclick=()=>{project.actors=project.actors.filter(a=>a.id!==b.dataset.delete);save();renderActors()})}
$('#generateCastBtn').onclick=()=>{generateCast();toast('Suggested cast created')};$('#addActorBtn').onclick=()=>openActor();
function openActor(id){const a=project.actors.find(x=>x.id===id)||{id:'',name:'',role:'Main character',age:30,gender:'Woman',look:'Filipino actor, expressive brown eyes, black hair, modest contemporary clothing',personality:'Matapang, mabait at determinado'};$('#actorId').value=a.id;$('#actorName').value=a.name;$('#actorRole').value=a.role;$('#actorAge').value=a.age;$('#actorGender').value=a.gender;$('#actorLook').value=a.look;$('#actorPersonality').value=a.personality;$('#actorModal').classList.remove('hidden')}
$('#closeActorModal').onclick=()=>$('#actorModal').classList.add('hidden');$('#actorModal').onclick=e=>{if(e.target.id==='actorModal')e.currentTarget.classList.add('hidden')};
$('#actorForm').onsubmit=e=>{e.preventDefault();const a={id:$('#actorId').value||uid(),name:$('#actorName').value.trim(),role:$('#actorRole').value.trim(),age:+$('#actorAge').value,gender:$('#actorGender').value,look:$('#actorLook').value.trim(),personality:$('#actorPersonality').value.trim()};const i=project.actors.findIndex(x=>x.id===a.id);i<0?project.actors.push(a):project.actors[i]=a;save();renderActors();$('#actorModal').classList.add('hidden');toast('Actor saved')};

function generateTreatment(){const hero=project.actors[0]?.name||'ang pangunahing tauhan',support=project.actors[1]?.name||'isang kaibigan';project.treatment=`PAMAGAT: ${project.title}\nGENRE: ${project.genre}\nTONO: ${project.ending} ending · ${project.audience}\n\nLOGLINE\n${project.idea}\n\nSIMULA\nIpakilala si ${hero} sa isang pangkaraniwang araw sa Pilipinas. Ipakita agad ang pangarap, takot, at mahalagang relasyon ng pangunahing tauhan. Isang hindi inaasahang pangyayari ang sisira sa normal niyang mundo.\n\nGITNA\nHabang sinusubukan ni ${hero} na lutasin ang problema, lalong lumalaki ang kapalit. Tutulong si ${support}, ngunit isang maling desisyon ang magdadala sa kanila sa pinakamababang punto. Dito mahaharap ang pangunahing tauhan sa katotohanang matagal niyang iniiwasan.\n\nKASUKDULAN\nKailangang pumili ni ${hero}: manatili sa takot o gawin ang tama kahit walang kasiguruhan. Ang desisyong ito ang magpapakita ng tunay na tema ng kuwento.\n\nWAKAS\nMagbigay ng ${project.ending.toLowerCase()} na pagtatapos. Ipakita ang pagbabago sa tauhan sa pamamagitan ng isang simpleng visual callback mula sa unang eksena.\n\nMENSAHE\nAng pag-asa ay hindi kawalan ng problema—ito ang pagpiling magpatuloy at magmahal sa gitna nito.`}
function renderScript(){if(!project.treatment)generateTreatment();$('#scriptTitle').textContent=project.title||'Untitled Movie';$('#scriptGenre').textContent=project.genre;$('#scriptLength').textContent=`${project.duration} minutes`;$('#treatment').value=project.treatment}
$('#treatment').oninput=e=>{project.treatment=e.target.value;queueSave()};$('#regenerateScriptBtn').onclick=()=>{generateTreatment();renderScript();save();toast('Treatment regenerated')};

function generateScenes(){const n=Math.max(5,Math.round(+project.duration*1.2)),hero=project.actors[0]?.name||'Pangunahing Tauhan',support=project.actors[1]?.name||'Kaibigan';const beats=[['Ang Mundong Kilala','Ipakilala ang pangunahing tauhan at ang kanyang pang-araw-araw na mundo.',`${hero}: “Akala ko, magiging maayos ang lahat ngayong araw.”`],['Ang Hindi Inaasahan','Dumating ang pangyayaring magpapabago sa lahat.',`${support}: “May kailangan kang malaman.”`],['Unang Hakbang','Nagpasya ang pangunahing tauhan na harapin ang problema.',`${hero}: “Hindi ko alam kung kaya ko, pero susubukan ko.”`],['Mas Mabigat na Pagsubok','Nagkaroon ng pagkakamali at lumaki ang panganib.',`${hero}: “Kasalanan ko ito. Pero hindi pa huli ang lahat.”`],['Ang Pagpili','Hinarap ng pangunahing tauhan ang pinakamahirap na desisyon.',`${support}: “Anuman ang piliin mo, huwag mong kalimutan kung sino ka.”`],['Bagong Liwanag','Ipakita ang resulta, pagbabago at mensahe ng kuwento.',`${hero}: “Hindi man nawala ang ulan, natutuhan kong hanapin ang liwanag.”`]];project.scenes=Array.from({length:n},(_,i)=>{const b=beats[Math.round(i*(beats.length-1)/(n-1))];return{id:uid(),title:`Eksena ${i+1}: ${b[0]}`,action:b[1],dialogue:b[2],prompt:`${project.visualStyle}, cinematic Filipino setting, ${project.actors.map(a=>a.name+': '+a.look).join('; ')}, scene: ${b[1]}, expressive lighting, consistent character design, 16:9, no text`}})}
function renderScenes(){if(!project.scenes.length)generateScenes();$('#sceneCount').textContent=`${project.scenes.length} scenes`;$('#sceneList').innerHTML=project.scenes.map((s,i)=>`<article class="scene-card" data-scene="${s.id}"><div class="scene-number"><small>SCENE</small><strong>${String(i+1).padStart(2,'0')}</strong></div><div class="scene-content"><div class="scene-head"><input data-key="title" value="${attr(s.title)}" aria-label="Scene title"><button class="delete-button" data-remove="${s.id}">Remove</button></div><div class="scene-fields"><label class="full">ACTION<textarea data-key="action" rows="3">${esc(s.action)}</textarea></label><label>DIALOGUE<textarea data-key="dialogue" rows="4">${esc(s.dialogue)}</textarea></label><label>IMAGE PROMPT<textarea data-key="prompt" rows="4">${esc(s.prompt)}</textarea></label></div></div></article>`).join('');$$('[data-scene] input,[data-scene] textarea').forEach(el=>el.oninput=()=>{const s=project.scenes.find(x=>x.id===el.closest('[data-scene]').dataset.scene);s[el.dataset.key]=el.value;queueSave()});$$('[data-remove]').forEach(b=>b.onclick=()=>{project.scenes=project.scenes.filter(s=>s.id!==b.dataset.remove);save();renderScenes()})}
$('#addSceneBtn').onclick=()=>{project.scenes.push({id:uid(),title:`Eksena ${project.scenes.length+1}: Bagong Eksena`,action:'Ilarawan ang nangyayari sa eksenang ito.',dialogue:'TAUHAN: “Ilagay ang dialogue dito.”',prompt:`${project.visualStyle}, Filipino setting, cinematic lighting, 16:9, no text`});save();renderScenes()};

function productionText(){return `${project.title.toUpperCase()}\nDe Mayo AI Movie Studio Production Plan\n\nGenre: ${project.genre}\nLength: ${project.duration} minutes\nAudience: ${project.audience}\nStyle: ${project.visualStyle}\n\nSTORY IDEA\n${project.idea}\n\nCAST\n${project.actors.map(a=>`${a.name} — ${a.role}, age ${a.age}\nAppearance: ${a.look}\nPersonality: ${a.personality}`).join('\n\n')}\n\nSTORY TREATMENT\n${project.treatment}\n\nSCENES\n${project.scenes.map((s,i)=>`SCENE ${i+1}: ${s.title}\nAction: ${s.action}\nDialogue: ${s.dialogue}\nVisual prompt: ${s.prompt}`).join('\n\n')}\n\nCreated with De Mayo AI Movie Studio.`}
function download(name,data,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
$('#downloadTxtBtn').onclick=()=>download(`${slug(project.title)}-production-script.txt`,productionText());$('#downloadJsonBtn').onclick=()=>download(`${slug(project.title)}-project.json`,JSON.stringify(project,null,2),'application/json');
$('#youtubeBtn').onclick=()=>{const text=`TITLE\n${project.title} | Original Tagalog AI-Animated Story\n\nDESCRIPTION\nIsang original na kuwentong Tagalog tungkol sa ${project.genre.toLowerCase()}, pag-asa at mga desisyong humuhubog sa ating buhay.\n\nAng pelikulang ito ay gumagamit ng AI-assisted fictional characters, illustrations at production tools. Walang tunay na tao o pangyayari ang inilalarawan maliban kung malinaw na sinabi.\n\nCreated by De Mayo AI Movie Studio.\n\nHASHTAGS\n#KwentongTagalog #TagalogStory #AIMovie #FilipinoStories #DeMayoMovieStudio`;$('#youtubeText').value=text;$('#youtubePackage').classList.remove('hidden');toast('YouTube package created')};$('#copyPackageBtn').onclick=()=>navigator.clipboard.writeText($('#youtubeText').value).then(()=>toast('Copied'));
$('#restoreInput').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());project={...blank,...data};save();syncForm();toast('Project restored');showView('home')}catch{toast('This backup could not be restored')}};
$('#newProjectBtn').onclick=()=>{if(confirm('Start a new movie? Download a backup first if you want to keep this project.')){project={...blank,actors:[],scenes:[]};save();syncForm();showView('home');toast('New project ready')}};
function esc(v=''){return String(v).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}function attr(v=''){return esc(v).replace(/"/g,'&quot;')}function slug(v='movie'){return(v||'movie').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'movie'}
syncForm();
